"""Shared dimensions and tensor-shape templates for VET-C v0.1."""

from __future__ import annotations

from typing import TypeAlias

ShapeTemplate: TypeAlias = tuple[int | None, ...]

BATCH_DIM: None = None
TIME_DIM: None = None

IMAGE_HEIGHT = 64
IMAGE_WIDTH = 64

RGB_CHANNELS = 3
DEPTH_CHANNELS = 1
FLOW_CHANNELS = 2
GPS_DIM = 3

SENSOR_HISTORY_STEPS = 32
IMU_DIM = 6
BATTERY_DIM = 1
MOTOR_STATE_DIM = 4

EXT_OBS_CHANNELS = RGB_CHANNELS + DEPTH_CHANNELS + FLOW_CHANNELS
INT_OBS_DIM = IMU_DIM + BATTERY_DIM + MOTOR_STATE_DIM

Z_EXT_CHANNELS = 128
Z_EXT_HEIGHT = 16
Z_EXT_WIDTH = 16
Z_INT_DIM = 128
FUSED_DIM = 256

RSSM_HIDDEN_DIM = 512
RSSM_LATENT_DIM = 64

SURPRISE_DIM = 1
KL_MAP_DIM = RSSM_LATENT_DIM
FUSION_ERROR_DIM = 1

REGIME_TOKEN_DIM = 96
PSI_FIELD_DIM = 5
MEMORY_TOKEN_DIM = 128
TRAJECTORY_FEATURE_DIM = 64
ACTION_DIM = 4

RGB_SHAPE: ShapeTemplate = (BATCH_DIM, RGB_CHANNELS, IMAGE_HEIGHT, IMAGE_WIDTH)
DEPTH_SHAPE: ShapeTemplate = (BATCH_DIM, DEPTH_CHANNELS, IMAGE_HEIGHT, IMAGE_WIDTH)
FLOW_SHAPE: ShapeTemplate = (BATCH_DIM, FLOW_CHANNELS, IMAGE_HEIGHT, IMAGE_WIDTH)
GPS_SHAPE: ShapeTemplate = (BATCH_DIM, GPS_DIM)

IMU_SHAPE: ShapeTemplate = (BATCH_DIM, SENSOR_HISTORY_STEPS, IMU_DIM)
BATTERY_SHAPE: ShapeTemplate = (BATCH_DIM, SENSOR_HISTORY_STEPS, BATTERY_DIM)
MOTOR_STATE_SHAPE: ShapeTemplate = (
    BATCH_DIM,
    SENSOR_HISTORY_STEPS,
    MOTOR_STATE_DIM,
)

EXT_OBS_SHAPE: ShapeTemplate = (
    BATCH_DIM,
    EXT_OBS_CHANNELS,
    IMAGE_HEIGHT,
    IMAGE_WIDTH,
)
INT_OBS_SHAPE: ShapeTemplate = (BATCH_DIM, SENSOR_HISTORY_STEPS, INT_OBS_DIM)

Z_EXT_SHAPE: ShapeTemplate = (
    BATCH_DIM,
    Z_EXT_CHANNELS,
    Z_EXT_HEIGHT,
    Z_EXT_WIDTH,
)
Z_INT_SHAPE: ShapeTemplate = (BATCH_DIM, Z_INT_DIM)
FUSED_SHAPE: ShapeTemplate = (BATCH_DIM, FUSED_DIM)

RSSM_H_SHAPE: ShapeTemplate = (BATCH_DIM, RSSM_HIDDEN_DIM)
Z_PRIOR_SHAPE: ShapeTemplate = (BATCH_DIM, RSSM_LATENT_DIM)
Z_POST_SHAPE: ShapeTemplate = (BATCH_DIM, RSSM_LATENT_DIM)

SURPRISE_SHAPE: ShapeTemplate = (BATCH_DIM, SURPRISE_DIM)
KL_MAP_SHAPE: ShapeTemplate = (BATCH_DIM, KL_MAP_DIM)
FUSION_ERROR_SHAPE: ShapeTemplate = (BATCH_DIM, FUSION_ERROR_DIM)

REGIME_TOKEN_SHAPE: ShapeTemplate = (BATCH_DIM, REGIME_TOKEN_DIM)
PSI_FIELD_SHAPE: ShapeTemplate = (BATCH_DIM, PSI_FIELD_DIM)
MEMORY_TOKENS_SHAPE: ShapeTemplate = (BATCH_DIM, MEMORY_TOKEN_DIM)
TRAJECTORY_SHAPE: ShapeTemplate = (BATCH_DIM, TIME_DIM, TRAJECTORY_FEATURE_DIM)
DENSITY_SHAPE: ShapeTemplate = (BATCH_DIM, TIME_DIM)
ACTION_SHAPE: ShapeTemplate = (BATCH_DIM, ACTION_DIM)

__all__ = [
    "ACTION_DIM",
    "ACTION_SHAPE",
    "BATTERY_DIM",
    "BATTERY_SHAPE",
    "BATCH_DIM",
    "DENSITY_SHAPE",
    "DEPTH_CHANNELS",
    "DEPTH_SHAPE",
    "EXT_OBS_CHANNELS",
    "EXT_OBS_SHAPE",
    "FLOW_CHANNELS",
    "FLOW_SHAPE",
    "FUSED_DIM",
    "FUSED_SHAPE",
    "FUSION_ERROR_DIM",
    "FUSION_ERROR_SHAPE",
    "GPS_DIM",
    "GPS_SHAPE",
    "IMAGE_HEIGHT",
    "IMAGE_WIDTH",
    "IMU_DIM",
    "IMU_SHAPE",
    "INT_OBS_DIM",
    "INT_OBS_SHAPE",
    "KL_MAP_DIM",
    "KL_MAP_SHAPE",
    "MEMORY_TOKEN_DIM",
    "MEMORY_TOKENS_SHAPE",
    "MOTOR_STATE_DIM",
    "MOTOR_STATE_SHAPE",
    "PSI_FIELD_DIM",
    "PSI_FIELD_SHAPE",
    "REGIME_TOKEN_DIM",
    "REGIME_TOKEN_SHAPE",
    "RGB_CHANNELS",
    "RGB_SHAPE",
    "RSSM_HIDDEN_DIM",
    "RSSM_H_SHAPE",
    "RSSM_LATENT_DIM",
    "SENSOR_HISTORY_STEPS",
    "ShapeTemplate",
    "SURPRISE_DIM",
    "SURPRISE_SHAPE",
    "TIME_DIM",
    "TRAJECTORY_FEATURE_DIM",
    "TRAJECTORY_SHAPE",
    "Z_EXT_CHANNELS",
    "Z_EXT_HEIGHT",
    "Z_EXT_SHAPE",
    "Z_EXT_WIDTH",
    "Z_INT_DIM",
    "Z_INT_SHAPE",
    "Z_POST_SHAPE",
    "Z_PRIOR_SHAPE",
]

